name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019] #ubuntu-latest, macos-latest, windows-2019
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setting Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Installing PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Check [clang-tidy, cppcheck]
        run: platformio check

      - name: Build
        run: platformio run

      - name: Running [test]
        run: |
          platformio test -e native

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.bin
          path: |
            .pio/build/esp32doit-devkit-v1/firmware.bin

  codecov:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setting Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Installing PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Checking [coverage]
        run: |
          platformio test -e native
          sudo apt-get install -y lcov ninja-build
          pip install lcov_cobertura
          lcov --capture --no-external --directory . --output-file coverage.info
          lcov --remove coverage.info
          lcov_cobertura coverage.info

      - name: Uploading to [codecov.io]
        uses: codecov/codecov-action@v3
        with:
          # gcov: true
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
