name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest] #macos-latest, windows-latest,
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run platformIO
        run: platformio check && platformio run

      - name: Running Test
        run: |
          platformio test -e native
          sudo apt-get install -y lcov ninja-build
          pip install lcov_cobertura
          lcov --capture --no-external --directory . --output-file coverage.info -e test/
          lcov_cobertura coverage.info
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # gcov: true
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.bin
          path: |
            .pio/build/esp32doit-devkit-v1/firmware.bin
      
