name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mariolopjr/pio:latest
    steps:
      - uses: actions/checkout@v2

      - name: Checking PIO
        run: |
          pio platform list
