name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ajaymikrotronik/test:latest
    steps:
      - uses: actions/checkout@v2

      - name: Checking PIO
        run: |
          ls -a
          cd /root/.platformio
          ls -a
