name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true
        gcov_include: main.cpp
        token: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
